### ISSUE TITLE
Studio broker per disaccopiamento dello stream di informazioni

### ISSUE THREAD

**Issue by Sadixo** [SevenBitsSwe/7BitsDocs#29]
Per questa componente il proponente suggerisce l’utilizzo piattaforme di event streaming, message brokers, o MQTT brokers (come ad esempio: Apache Kafka, RabbitMQ, HiveMQ)

**Comment by CodeUncas** [comment]
Aggiornamento compiti a seguito dell'incontro intermedio:
( analizzare le seguenti ,utilizzando python)

- [ ] creazione di un ambiente di simulazione adatto con docker compose
- [ ] Creazione dei topic con kafka
- [ ] Collegamento kafka con apache flink
- [ ] Serializzazione dati da kafka a clickhouse
@Sadixo @riky869 @giocri
